platform :ios, '15.0'

target 'MVVM_Clean_TestCases' do
  use_frameworks!

  pod 'ReachabilitySwift'

  target 'MVVM_Clean_TestCasesTests' do
    inherit! :search_paths
    pod 'ReachabilitySwift'
  end

  target 'MVVM_Clean_TestCasesUITests' do
    pod 'ReachabilitySwift'
  end

end
